version: '3'

services:
  wemeet:
    build: 
      context: .
      args:
        USER_ID: ${USER_ID}
    environment:
      - LANG=zh_CN.UTF-8
      - GTK_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - DBUS_SESSION_BUS_ADDRESS=unix:path=${USER_DBUS_SESSION_BUS_ADDRESS}
      - PULSE_SERVER=unix:${USER_PULSE_SERVER}
      - DISPLAY
      - XAUTHORITY=/home/user/.Xauthority
    volumes:
      - "${XAUTHORITY}:/home/user/.Xauthority:ro"
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - "${USER_DBUS_SESSION_BUS_ADDRESS}:${USER_DBUS_SESSION_BUS_ADDRESS}"
      - "${USER_PULSE_SERVER}:${USER_PULSE_SERVER}"
    hostname: ${HOSTNAME}
    command: 'wemeet'
    shm_size: 2gb
    ipc: host
